apiVersion: v1
kind: Service
metadata:
  name: {{ include "trustlink-indexer.fullname" . }}
  labels:
    {{- include "trustlink-indexer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.graphqlPort | default .Values.gqlPort }}
      targetPort: graphql
      protocol: TCP
      name: graphql
  selector:
    {{- include "trustlink-indexer.selectorLabels" . | nindent 4 }}
    {{- if .Values.main.enabled }}
    deployment-type: main
    {{- else }}
    deployment-type: standard
    {{- end }}