# These are supported funding model platforms

github: [Haroldwonder]
open_collective: # e.g., trustlink
patreon: # e.g., trustlink
tidelift: # e.g., npm/trustlink
custom: # e.g., ['https://www.paypal.me/trustlink']
