export { TrustLinkClient } from "./client.js";
export type {
  Attestation,
  AttestationOrigin,
  AttestationRequest,
  AttestationStatus,
  AttestationTemplate,
  AuditAction,
  AuditEntry,
  ClaimTypeInfo,
  ContractConfig,
  ContractMetadata,
  Council,
  CouncilProposal,
  Delegation,
  Endorsement,
  ExpirationHook,
  FeeConfig,
  GlobalStats,
  HealthStatus,
  IssuerMetadata,
  IssuerStats,
  IssuerTier,
  MultiSigProposal,
  Network,
  RequestStatus,
  StorageLimits,
  SubjectDataExport,
  Template,
  TrustLinkClientOptions,
  TtlConfig,
} from "./types.js";
export {
  TrustLinkError,
  AlreadyInitializedError,
  NotInitializedError,
  UnauthorizedError,
  NotFoundError,
  DuplicateAttestationError,
  AlreadyRevokedError,
  ExpiredError,
  InvalidExpirationError,
  InvalidTimestampError,
  InvalidFeeError,
  FeeTokenRequiredError,
  TooManyTagsError,
  TagTooLongError,
  InvalidThresholdError,
  NotRequiredSignerError,
  AlreadySignedError,
  ProposalFinalizedError,
  ProposalExpiredError,
  ContractPausedError,
  SubjectNotWhitelistedError,
  InvalidClaimTypeError,
  InvalidJurisdictionError,
  RateLimitedError,
  LimitExceededError,
  ProposalCancelledError,
  InvalidSourceReferenceError,
  parseTrustLinkError,
  classifyErrorCode,
  knownErrorCodes,
} from "./types.js";
export { CircuitBreaker, withRetry } from "./resilience.js";
export type { RetryOptions, CircuitBreakerOptions, ResilienceConfig } from "./resilience.js";
